spring:
  application:
    name: register-client
  datasource:
    url: jdbc:postgresql://localhost:5432/granprodb
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /glam-pro
